version: '3'

services:
  mysql:
    container_name: myworkout_db
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./init_sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"